<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function satellite_passage_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.satellite_passage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Satellite Aquasition Plan') . '</p>';
      return $output;

    default:
  }
}


// Implements hook_theme()
function satellite_passage_theme( $existing, $type, $theme, $path ){
    return [
        'satellite_passage-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'satellite_passage', // My template file name
            'variables' => [
                'site_name' => "Default",
                'helptext' => '',
              ],
        ],
    ];
}
