satellite_passage.configuration:
  type: config_object
  label: 'Sentinel Aquasition Plan  configuration'
  mapping:
    helptext:
      label: 'Help text to be displayed under the map'
      type: text_format
    language:
      type: string
      label: 'Language code'
